# Generated by Django 6.0.5 on 2026-05-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Line number shown on the bus.', max_length=20)),
                ('name', models.CharField(help_text='Short description of where it goes.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'buses',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text="Optional label (e.g. 'Work commute').", max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to='routes.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'bus'), name='routes_savedroute_unique_user_bus')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1 = first stop on the line, 2 = second, etc.')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.stop')),
            ],
            options={
                'ordering': ['bus', 'order'],
                'constraints': [models.UniqueConstraint(fields=('bus', 'order'), name='routes_routestop_unique_bus_order'), models.UniqueConstraint(fields=('bus', 'stop'), name='routes_routestop_unique_bus_stop')],
            },
        ),
    ]
